[package]
name = "txne"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
pcap = { version = "1.1.0", features = ["tokio"] }
axum = "0.6.18"
clap = { version = "4.3.11", features = ["derive"] }
